/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import { TextureLoader } from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Railways(props) {
  const { nodes, materials } = useGLTF('/actuallydone.glb')

  const textureLoader = new TextureLoader()

  const bakedTexture = textureLoader.load('/churchdown.jpg')
  bakedTexture.flipY = false
  bakedTexture.colorSpace = THREE.SRGBColorSpace
 
  const bakedMaterial = new THREE.MeshBasicMaterial({map: bakedTexture})

  const bakedTextureone = textureLoader.load('/grounddown.jpg')
  bakedTextureone.flipY = false
  bakedTextureone.colorSpace = THREE.SRGBColorSpace
 
  const bakedMaterialone = new THREE.MeshBasicMaterial({map: bakedTextureone}) 

  const bakedTexturetwo = textureLoader.load('/tatti.jpg')
  bakedTexturetwo.flipY = false
  bakedTexturetwo.colorSpace = THREE.SRGBColorSpace
 
  const bakedMaterialtwo = new THREE.MeshBasicMaterial({map: bakedTexturetwo})       

  return (
    <group {...props} dispose={null}>
      <mesh
        name="��������_�����������021"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������021'].geometry}
        material={materials.material}
      />
      <mesh
        name="��������_�����������026"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������026'].geometry}
        material={materials.material}
      />
      <mesh
        name="��������_�����������027"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������027'].geometry}
        material={materials.material}
      />
      <mesh
        name="��������_�����������028"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������028'].geometry}
        material={materials.material}
      />
      <mesh
        name="��������_�����������029"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������029'].geometry}
        material={materials.material}
      />
      <mesh
        name="��������_�����������052"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������052'].geometry}
        material={materials['.14_0']}
      />
      <mesh
        name="��������_�����������053"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������053'].geometry}
        material={bakedMaterialtwo}
        position={[-15.814, 0, 0]}
        scale={1.3}
      />
      <mesh
        name="��������_�����������066"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������066'].geometry}
        material={materials['.11_1']}
        position={[59.209, 0, 0]}
      />
      <mesh
        name="��������_�����������067"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������067'].geometry}
        material={materials['.11_1']}
        position={[-10.929, 0, 0]}
      />
      <mesh
        name="��������_�����������011"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������011'].geometry}
        material={materials.material_31}
      />
      <mesh
        name="��������_�����������024"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������024'].geometry}
        material={materials['.8_3']}
        position={[-15.814, 0, 0]}
        scale={1.3}
      />
      <mesh
        name="��������_�����������058"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������058'].geometry}
        material={materials['.3_0']}
      />
      <mesh
        name="��������_�����������059"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������059'].geometry}
        material={materials.material}
      />
      <mesh
        name="��������_�����������062"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������062'].geometry}
        material={materials.Material}
      />
      <mesh
        name="��������_�����������006"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������006'].geometry}
        material={bakedMaterialone}
      />
      <mesh
        name="��������_�����������004"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������004'].geometry}
        material={materials['.11_1']}
        position={[-20.26, 0, 0]}
      />
      <mesh
        name="��������_�����������005"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������005'].geometry}
        material={materials['.14_0']}
      />
      <mesh
        name="��������_�����������007"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������007'].geometry}
        material={materials['.14_0']}
      >
        <meshBasicMaterial/>
        </mesh>
      <mesh
        name="��������_�����������008"
        castShadow
        receiveShadow
        geometry={nodes['��������_�����������008'].geometry}
        material={materials['Material.001']}
      />
      <mesh
        name="windows"
        castShadow
        receiveShadow
        geometry={nodes.windows.geometry}
        material={materials.material_30}
        position={[18.085, 0, 0]}
      />
      <mesh
        name="mainbuilding"
        castShadow
        receiveShadow
        geometry={nodes.mainbuilding.geometry}
        material={bakedMaterial}
        position={[18.085, 0, 0]}
      />
      <mesh
        name="base"
        castShadow
        receiveShadow
        geometry={nodes.base.geometry}
        material={materials.material_3}
        position={[18.085, 0, 0]}
      />
      <mesh
        name="pillars"
        castShadow
        receiveShadow
        geometry={nodes.pillars.geometry}
        material={materials.material_31}
        position={[18.085, 0, 0]}
      />
      <mesh
        name="roofsecond"
        castShadow
        receiveShadow
        geometry={nodes.roofsecond.geometry}
        material={materials.material}
        position={[18.085, 0, 0]}
      />
      <group name="roofmain" position={[18.085, 0, 0]}>
        <mesh
          name="��������_�����������007_1"
          castShadow
          receiveShadow
          geometry={nodes['��������_�����������007_1'].geometry}
          material={materials['.8_0']}
        />
        <mesh
          name="��������_�����������007_2"
          castShadow
          receiveShadow
          geometry={nodes['��������_�����������007_2'].geometry}
          material={materials['.8_3']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/actuallydone.glb')
